spring.application.name=kitchenmanagement
spring.data.mongodb.database=smartkitchen
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
gemini.api.key = AIzaSyBAwoFHUsBVFbddq106xdrY-5dHWUPjgFk

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amarkulkarni789@gmail.com
spring.mail.password=jujp txmn nwaf nppt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
