spring.application.name=kitchenmanagement
spring.data.mongodb.database=smartkitchen
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
gemini.api.key = AIzaSyBAwoFHUsBVFbddq106xdrY-5dHWUPjgFk
